# Generated by Django 5.2.3 on 2025-07-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='department',
        ),
    ]
