# Generated by Django 5.2.3 on 2025-06-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('variant', 'size')},
        ),
    ]
