# Generated by Django 5.2.3 on 2025-07-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
