# Generated by Django 5.2.3 on 2025-07-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
